#!/bin/sh

# Execute a file named 'compiled' (in the current directory) to run the script.
# The file 'compiled' is the output of running ./compile against the script's
# source code.
#
# If script execution succeeds, exit 0.
# If script execution fails, exit non-zero.
# Content appended to a file named 'log' (in the current directory) appears
# in the script's request log.

echo todo
